name: CI

on:
  push:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Git - Checkout
        uses: actions/checkout@v3

      - name: Install just
        uses: taiki-e/install-action@just

      - name: Install zsh
        run: sudo apt update && sudo apt install -y zsh
      
      - name: Build image
        run: just build

      - name: Run image
        run: |
          export APP_API_KEYS=""
          export TRANSLATE_API_KEY=""
          just run

      - name: Health check
        run: just health-check

  test:
    name: Test
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Git - Checkout
        uses: actions/checkout@v3

      - name: Install just
        uses: taiki-e/install-action@just

      - name: Test
        run: just test
