name: CI

on:
  push:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy
    timeout-minutes: 10
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Git - Checkout
        uses: actions/checkout@v3

      - name: Install just
        uses: taiki-e/install-action@just
      
      - name: Build image
        run: just build

      - name: Tag image
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          COMMIT_SHA: ${{ github.sha }}
        run: just tag-image

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Configure Docker
        run: gcloud auth configure-docker

      - name: Push image
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          COMMIT_SHA: ${{ github.sha }}
        run: just push-image

      - name: Deploy Cloud Run service
        uses: google-github-actions/deploy-cloudrun@v1
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          COMMIT_SHA: ${{ github.sha }}
        with:
          service: pocket-slate-api
          image: "gcr.io/$GCP_PROJECT_ID/pocket-slate-api:$COMMIT_SHA"

      - name: Use deployment URL
        run: 'curl "${{ steps.deploy.outputs.url }}"'
